import Head from "next/head";
import { Inter } from "next/font/google";
import Hero from "@/components/home/Hero";
import Nails_Cntr from "@/components/home/Nails_Cntr";
import ShopCards_section from "@/components/home/shopCards_home/ShopCards_section";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Nails_Cntr />
        <ShopCards_section />
      </main>
    </>
  );
}
